version: '3.4'

services:
  application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000"
      - "5001"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro